export const PAYMENT_METCHOD_CASH="CASH";
export const PAYMENT_METCHOD_CARD="CARD";
export const PAYMENT_METCHOD_ONLINE="ONLINE";

export const PAYMENT_STATUS_PENDING="PENDING";
export const PAYMENT_STATUS_SUCCESS="SUCCESS";
export const PAYMENT_STATUS_FAILED="FAILED";